import type { Metadata } from 'next';
import { Roboto, Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  subsets: ['latin'], // Supports Latin characters
  weight: ['400', '600', '700', '500'], // Choose font weights as needed
  variable: '--font-poppins', // Optional: Define CSS variable
});
const roboto = Roboto({
  subsets: ['latin'], // Supports Latin characters
  weight: ['400', '600', '700', '500'], // Choose font weights as needed
  variable: '--font-roboto', // Optional: Define CSS variable
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} ${roboto.variable}  antialiased`}>
        <Toaster position='top-right' />
        {children}
      </body>
    </html>
  );
}
