const ENDPOINTS = {
  BASE: process.env.NEXT_PUBLIC_API_URL + '/api',
  AUTH: 'auth',
  AUTH_VERIFY: 'auth/verify',
  UPLOAD: 'upload',
  ACTIVITIES: 'activities',
  DESTINATIONS: 'destinations',
  PACKAGES: 'packages',
  CAROUSELS: 'carousels',
  NAV_ITEMS: 'activities/nav-items',
  REVIEWS: 'reviews',
  FAQ: 'faqs',
  BLOGS: 'blogs',
  AUTHORS: 'authors',
  BOOKING: 'booking',
  MAIL: 'mail',
  SITE_INFO: 'site-info',
  CATEGORIES: 'categories',
  PAYMENT_STRIPE_INTENT: 'payment/stripe/create-intent',
  PAYMENT_STRIPE_CONFIRM: 'payment/stripe/confirm',
  PAYMENT_PAYPAL_ORDER: 'payment/paypal/create-order',
  PAYMENT_PAYPAL_CAPTURE: 'payment/paypal/capture',
  PAYMENT_CASH: 'payment/cash',
  PAYMENT_CANCEL: 'payment/cancel',
  PAYMENT_REFUND: 'payment/refund',
  PAYMENT_STATUS: 'payment/status',
  TEAM: 'team',
  NEWSLETTER_SUBSCRIBE: 'newsletter/subscribe',
  NEWSLETTER_UNSUBSCRIBE: 'newsletter/unsubscribe',
  COMMENTS: 'comments',
  COMMENTS_APPROVED: 'comments/approved',
  WISHLIST: 'wishlist',
};

export default ENDPOINTS;
